version: 2.1

jobs:
  build:
    docker:
      - image: ruby:3.0.0
    steps:
      - checkout
      - run:
          name: Sleep for 1 min
          command: sleep 60
  api_tests:
    docker:
      - image: ruby:3.0.0
    steps:
      - checkout
      - run:
          name: Sleep for 30 sec
          command: sleep 30
  package:
    docker:
      - image: ruby:3.0.0
    steps:
      - checkout
      - run:
          name: Sleep for 1 min
          command: sleep 60
  deploy:
    docker:
      - image: ruby:3.0.0
    steps:
      - checkout
      - run:
          name: Sleep for 30 sec
          command: sleep 30

workflows:
  pipeline:
    jobs:
      - build
      - api_tests:
          requires:
            - build
      - package:
          requires:
            - api_tests
      - deploy_approval:
          type: approval
          requires:
            - package
      - deploy:
          requires:
            - deploy_approval
